# Generated by Django 4.2 on 2023-05-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycmp', '0002_directory_parent_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesection',
            name='owner',
        ),
        migrations.AddField(
            model_name='filesection',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mycmp.file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mycmp.directory'),
        ),
    ]
