# Generated by Django 4.2 on 2023-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mycmp", "0004_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
