# Generated by Django 4.2 on 2023-05-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mycmp", "0006_remove_file_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filesection",
            old_name="end_line",
            new_name="begin",
        ),
        migrations.RenameField(
            model_name="filesection",
            old_name="start_line",
            new_name="end",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="availability_date",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="end_char",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="section_status",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="section_type",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="start_char",
        ),
        migrations.RemoveField(
            model_name="filesection",
            name="status_data",
        ),
        migrations.AddField(
            model_name="filesection",
            name="create_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="filesection",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filesection",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mycmp.file"
            ),
        ),
        migrations.AlterField(
            model_name="filesection",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name="SectionStatus",
        ),
        migrations.DeleteModel(
            name="SectionType",
        ),
        migrations.DeleteModel(
            name="StatusData",
        ),
    ]
